apiVersion: v1
kind: Service
metadata:
  name: lookerbot
  namespace: lookerbot-dev
spec:
  selector:
    app: lookerbot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3333
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lookerbot
  namespace: lookerbot-dev
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: lookerbot.k8s.dev.kargo.com
      http:
        paths:
          - backend:
              serviceName: lookerbot
              servicePort: 80
